### ISSUE TITLE
Don't just ignore golden cards

### ISSUE THREAD

**Issue by dgstranz** [Freezard/hs-collection-tracker#45]
A player may be lucky and get a golden card before getting the normal version of the same card. It should be counted in the Progress spreadsheet even though "I don't care about golden" is checked.

**Comment by Freezard** [comment]
Yes that makes sense. I will add so that golden cards act as normal cards when that option is enabled.

**Comment by Freezard** [comment]
On a second thought I will keep it as it is. If you don't care about golden cards, chances are that you have so few golden cards that you can track the stats manually or that you will disenchant them sooner or later anyway. Exclude golden cards is a good way for users to only see normal data, and involving stray golden cards will make it so that users can't compare only normal data anymore.
